### PR TITLE
docs: add an example: How to use RxPY to prepare batches by maximum bytes count.

### LINKED ISSUE #392: Split requests for max-body-size
__Proposal:__
You can specify the max body size of the influxdb and the client split the data points into correct batches.

__Current behavior:__
If you try to sent a bigger batch of datapoints with
``` client.write_points(points)```. 

You get the error message: 

```influxdb.exceptions.InfluxDBClientError: 413: <html>
<head><title>413 Request Entity Too Large</title></head>
<body>
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx/1.17.4</center>
</body>
</html>
```
This already happen if the plain data points only have 1.500.000 bytes.

__Desired behavior:__
The client check the size of the body and split the data into different requests if necessary.

__Use case:__
We are not the owner of the influxdb instance and can not change the max-body-size.
But it's also hard to calculate the bytes of the body, because the body is created in this library.
Further the byte size of our data points are very different.
So it's very hard to find a good batch size for all our datapoints.

### PR DESCRIPTION
**Pull request by bednar**
Closes #392

## Proposed Changes

Added an example: `How to use RxPY to prepare batches by maximum bytes count.`

## Checklist

- [x] CHANGELOG.md updated
- [x] Rebased/mergeable
- [x] A test has been added if appropriate
- [x] `pytest tests` completes successfully
- [x] Commit messages are in [semantic format](https://seesparkbox.com/foundry/semantic_commit_messages)
- [x] Sign [CLA](https://www.influxdata.com/legal/cla/) (if not already signed)

### CODE REVIEW

**Review by powersj — APPROVED** [review]
agreed on not modifying the underlying library for this. The example looks good!

**Comment by powersj** [comment]
@rhajek thoughts on this one?

**Comment by rhajek** [comment]
The example as a workaround is ok.

**Comment by powersj** [comment]
> The example as a workaround is ok.

Thanks

@bednar can you update the README change for this PR and we can land this?

**Comment by bednar** [comment]
@powersj the sources are rebased and updated to `RxPY`  `v4.0.4`

**Review by rhajek — APPROVED** [review]

**Review by powersj — APPROVED** [review]
thank you!

**Pull request merged**
