### PR TITLE
fix: prevent creating unnecessary threads repeatedly

### PR DESCRIPTION
**Pull request by goznauk**
Closes https://github.com/influxdata/influxdb-client-python/issues/561

## Checklist

- [x] CHANGELOG.md updated
- [x] Rebased/mergeable
- [x] `pytest tests` completes successfully
- [x] Commit messages are [conventional](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] Sign [CLA](https://www.influxdata.com/legal/cla/) (if not already signed)

### CODE REVIEW

**Review by bednar — CHANGES_REQUESTED** [review]
@goznauk thanks for your PR 👍. Can you please satisfy following Checklist:

image

**Comment by goznauk** [comment]
@bednar Thank you for your feedback! I have completed all the items in the checklist as requested. Please let me know if there are any other requirements or changes needed for this PR.

**Comment by bednar** [comment]
@goznauk thanks

**Review by bednar — APPROVED** [review]

**Comment by bednar** [comment]
@goznauk, I've added this PR to our backlog. We need to conduct a few manual tests on our end before we can proceed with merging this PR.

**Comment by bednar** [comment]
@goznauk I've tested this PR and everything looks good

**Pull request merged**
