### PR TITLE
Anais pandas

### LINKED ISSUE #37: Add build_flux_query functionality
Not sure how you want to structure tests, but here it is: 
Test for build_flux_query:
https://github.com/influxdata/influxdb-client-python-pandas/blob/master/test_flux_query.py

### LINKED ISSUE #38: Add conversion to line protocol
Test for line protocol: 
https://github.com/influxdata/influxdb-client-python-pandas/blob/master/test_line_protocol.py

### PR DESCRIPTION
**Pull request by Anaisdg**
Closes #37 Closes #38 

_Briefly describe your proposed changes:_

  - [ ] CHANGELOG.md updated
  - [ ] Rebased/mergeable
  - [ ] Tests pass
  - [ ] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

**Comment by bednar** [comment]
Hi @Anaisdg,

thanks for contribution.

Could you please do a few improvements that will be useful for consistency in client API?

#### Add conversion to line protocol

The best approach for that is integrate its into `WriteApi`: https://github.com/influxdata/influxdb-client-python/blob/50b0b367ad0b4ce3ca8aeb4e225e1b08ba00b004/influxdb_client/client/write_api.py#L155

...so users could directly write `DataFrame` by:

```python
data = {"measurement": ["measurement"], "tag_key": ["key"], "tag_value": ["value"], "field_key": ["field"],
        "field_value": [6],
        "datetime": [datetime(2011, 5, 25, 14)]}
df_ex = pd.DataFrame.from_dict(data)

write_api.write(org="my-org", bucket="my-bucket", record=df_ex,
                data_frame_options={"measurement": "measurement",
                                    "tags": [{"tag_key": "tag_value"}],
                                    "fields": [{"field_key": "field_value"}],
                                    "time": "datetime"})
```

just add new type of serialisation there: https://github.com/influxdata/influxdb-client-python/blob/50b0b367ad0b4ce3ca8aeb4e225e1b08ba00b004/influxdb_client/client/write_api.py#L210

https://github.com/influxdata/influxdb-client-python/blob/50b0b367ad0b4ce3ca8aeb4e225e1b08ba00b004/influxdb_client/client/write_api.py#L233

something like:

```python
...
elif isinstance(record, DataFrame):
     _result = self._serialize(lp(record, data_frame_options))
...
```

Regards

**Comment by bednar** [comment]
Hi @Anaisdg,

in builder pattern we should use [stream parameters](https://v2.docs.influxdata.com/v2.0/query-data/get-started/syntax-basics/#define-data-stream-variables) instead of directly replacing strings. 

That avoid problem with query injection... so result from `qBuilder` should be something like this:

```
bucket = "github"
rangeStart = -1h
rangeEnd = now()
measurement = "github_repository"
field = "size"

from(bucket: bucket)
  |> range(start: rangeStart, stop: rangeEnd)
  |> filter(fn: (r) => r._measurement == measurement)
  |> filter(fn: (r) => r._field == field)
```

Regards

**Comment by Anaisdg** [comment]
@bednar, 
How do you expect that structure to look like for multiple tag keys and tag fields? Thanks

**Comment by bednar** [comment]
@Anaisdg 

```python
q3 = qBuilder().filters(filters=[("_measurement", ["abc", "def"]), ("key", ["value", "value_2"])])
```

should be something like this:

```sql
_measurement_param_1 = "abc"
_measurement_param_2 = "def"
_key_param_1 = "value"
_key_param_2 = "value_2"


|> filter(fn: (r) => r._measurement == _measurement_param_1 or r._measurement == _measurement_param_2)
|> filter(fn: (r) => r.key == _key_param_1 or r.key == _key_param_2)
```

**Pull request closed without merging**
