### PR TITLE
fix: set proxy server in config file

### PR DESCRIPTION
**Pull request by dstaesse**
The proxy option was not parsed in the config file.

Closes #

## Proposed Changes

_Briefly describe your proposed changes:_

## Checklist

- [x] CHANGELOG.md updated
- [x] Rebased/mergeable
- [x] A test has been added if appropriate
- [x] `pytest tests` completes successfully
- [x] Commit messages are in [semantic format](https://seesparkbox.com/foundry/semantic_commit_messages)
- [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

**Comment by dstaesse** [comment]
I had a bit of a headache today figuring out why I couldn't connect to my InfluxDB server from behind a proxy. I fixed it for the config.ini, but I would also take into account http_proxy and HTTP_PROXY environment variables if they are set, with lower precedence (these are now ignored) Since there are some options how to deal with that, I'll leave that one up to you guys.

**Review by bednar — CHANGES_REQUESTED** [review]
Thanks for your PR 👍 

Could you please satisfy next requirements before we merge the PR into master:

1. Add test for `proxy` configuration: https://github.com/dstaesse/influxdb-client-python/blob/adcb7bed4428bab5937c6bea2131628839f924c1/tests/test_InfluxDBClient.py#L65
2. Sign CLA: image

**Comment by dstaesse** [comment]
Sure.

**Comment by dstaesse** [comment]
I looked for a valid proxy configuration for the integration tests, but it looks like there is no test yet for the proxy feature as a whole...
Adding that is a bit beyond the scope of my intended contribution here...

**Comment by bednar** [comment]
> Adding that is a bit beyond the scope of my intended contribution here...

Your test: `test_init_from_file_proxy` is quite enough. Thx

**Review by bednar — APPROVED** [review]
@dstaesse thanks again for your PR! 👍 Let's merge it into master.

**Pull request merged**
